# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rfsrs_wrappers", use_symbols = TRUE, package_name = "rfsrs")

#' @usage NULL
#' @useDynLib rfsrs, .registration = TRUE
NULL

#' Get default FSRS parameters (21 values for FSRS-6)
#' @export
fsrs_default_parameters <- function() .Call(wrap__fsrs_default_parameters)

#' Calculate next interval for target retention
#' @param stability Current stability
#' @param desired_retention Target retention (0.0-1.0)
#' @param params Optional custom parameters (21 values). Uses defaults if NULL.
#' @export
fsrs_next_interval <- function(stability, desired_retention, params = NULL) .Call(wrap__fsrs_next_interval, stability, desired_retention, params)

#' Initial memory state for new card
#' @param rating Rating: 1=Again, 2=Hard, 3=Good, 4=Easy
#' @param params Optional custom parameters (21 values). Uses defaults if NULL.
#' @export
fsrs_initial_state <- function(rating, params = NULL) .Call(wrap__fsrs_initial_state, rating, params)

#' Next memory state after review
#' @param stability Current stability
#' @param difficulty Current difficulty  
#' @param elapsed_days Days since last review
#' @param rating Rating: 1=Again, 2=Hard, 3=Good, 4=Easy
#' @param params Optional custom parameters (21 values). Uses defaults if NULL.
#' @export
fsrs_next_state <- function(stability, difficulty, elapsed_days, rating, params = NULL) .Call(wrap__fsrs_next_state, stability, difficulty, elapsed_days, rating, params)

#' Get all four rating outcomes at once (like py-fsrs repeat())
#' @param stability Current stability (NULL for new card)
#' @param difficulty Current difficulty (NULL for new card)  
#' @param elapsed_days Days since last review (0 for new card)
#' @param desired_retention Target retention for interval calculation
#' @param params Optional custom parameters (21 values). Uses defaults if NULL.
#' @return List with $again, $hard, $good, $easy, each containing stability, difficulty, interval
#' @export
fsrs_repeat <- function(stability = NULL, difficulty = NULL, elapsed_days, desired_retention, params = NULL) .Call(wrap__fsrs_repeat, stability, difficulty, elapsed_days, desired_retention, params)

#' Calculate retrievability (recall probability)
#' @param stability Card stability
#' @param elapsed_days Days since last review
#' @export
fsrs_retrievability <- function(stability, elapsed_days) .Call(wrap__fsrs_retrievability, stability, elapsed_days)

#' Vectorized retrievability calculation
#' @param stability Vector of stability values
#' @param elapsed_days Vector of elapsed days (same length as stability)
#' @export
fsrs_retrievability_vec <- function(stability, elapsed_days) .Call(wrap__fsrs_retrievability_vec, stability, elapsed_days)

#' Convert SM-2 ease factor and interval to FSRS memory state
#' @param ease_factor SM-2 ease factor (typically 1.3-3.0)
#' @param interval Current interval in days
#' @param sm2_retention Assumed retention rate for SM-2 (default 0.9)
#' @param params Optional custom parameters (21 values). Uses defaults if NULL.
#' @export
fsrs_from_sm2 <- function(ease_factor, interval, sm2_retention, params = NULL) .Call(wrap__fsrs_from_sm2, ease_factor, interval, sm2_retention, params)

#' Compute memory state from review history
#' @param ratings Vector of ratings (1-4) in chronological order
#' @param delta_ts Vector of days since previous review (0 for first review)
#' @param initial_stability Optional starting stability (for SM-2 migration)
#' @param initial_difficulty Optional starting difficulty (for SM-2 migration)
#' @param params Optional custom parameters (21 values). Uses defaults if NULL.
#' @export
fsrs_memory_state <- function(ratings, delta_ts, initial_stability = NULL, initial_difficulty = NULL, params = NULL) .Call(wrap__fsrs_memory_state, ratings, delta_ts, initial_stability, initial_difficulty, params)


# nolint end
